FROM alpine AS certs
RUN apk add -U \
    ca-certificates

FROM scratch

LABEL org.opencontainers.image.authors="Aleksei Potsetsuev <wrouds@gmail.com>"
LABEL org.opencontainers.image.title="mc-motd"
LABEL org.opencontainers.image.source="https://github.com/wroud/mc-motd"

COPY --from=certs /etc/ssl/certs/ /etc/ssl/certs
COPY mc-motd /
ENTRYPOINT ["/mc-motd"]
